name: Commiter

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches: 
      - main
  schedule:
      - cron: '* * * * *'

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps: 
      - name: start to commit
        uses: actions/checkout@v2
      - name: begin git
        run: |
          git config --global user.email "819464715@qq.com"
          git config --global user.name "tanruixiang"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull 
          nowtime=$( date )
          nowtime>>autocomitlist
          git add autocommitlist
          git commit -m " do it! "
          git push
